### ISSUE TITLE
Run the tests on push to safe-react dev

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-e2e-tests#21]
Since the suite now runs w/o failing, let's try to automate it for dev builds.

Whenever a push happens to the dev branch of safe-react, launch the tests against https://safe-team.dev.gnosisdev.com/app/#/welcome (rinkeby dev).

**Comment by juampibermani** [comment]
@katspaugh @dasanra I see that sometimes when loading a safe it takes an important amount of time to fetch the owners and transactions, making impossible to start executing transaccions(since the account doesn't have ownership yet). We should discuss how we solve this problem.
