### ISSUE TITLE
Add a "read-only" test that reviews a transaction

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-e2e-tests#50]
A test case that creates a transaction but doesn't submit it. Make assertions on the Review screen.
This'll allow us to check that the different API requests (gas, gas price etc) are working fine.

* [x] Create or adapt an existing test
* [x] Add it to the PR suite
* [x] Add assertions on gas estimation, advanced options etc

**Comment by katspaugh** [comment]
I've added a basic Send Funds test [here](https://github.com/gnosis/safe-react-e2e-tests/blob/7a31184b15a256fb21eb99cb3a0fc70bb2dc61ce/src/read_only/review_tx.test.js). We need to add more assertions on the gas estimation.

**Comment by francovenica** [comment]
The test creates a send funds tx, 
asserts the adv options sections. 
checks that the gas price and gas limit is not 0, 
edit those values and checks the price estimation message
edict the nonce to be a +2 of what is expected
checks that the warning message for nonce out of order

Used a branch that was already created by Diogo, so there is no new PR, just a new commit with the tests
https://github.com/gnosis/safe-react-e2e-tests/commit/88e6b0eb445938c5bcd4155d437dbb82e54d3e85
And another to rename of the file:
https://github.com/gnosis/safe-react-e2e-tests/commit/bb2c6ee8fc8ee209cff4dec1f60c6012279df4ff

**Comment by DiogoSoaress** [comment]
Done in https://github.com/gnosis/safe-react-e2e-tests/pull/94
