### ISSUE TITLE
Add eslint and prettier

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-e2e-tests#57]
Basically just copy this action – https://github.com/gnosis/safe-react/blob/dev/.github/workflows/lint.yml

And the corresponding configs:
https://github.com/gnosis/safe-react/blob/dev/.eslintrc.js
https://github.com/gnosis/safe-react/blob/dev/.prettierrc

Also configure husky to run the lint on each commit: https://github.com/gnosis/safe-react/blob/dev/.husky/pre-commit

**Comment by katspaugh** [comment]
@dasanra why did you close it? :)

**Comment by dasanra** [comment]
This is already done :+1:
