### ISSUE TITLE
Test with a pre-filled localStorage

### ISSUE THREAD

**Issue by katspaugh** [gnosis/safe-react-e2e-tests#58]
Save a snapshot of the localStorage into a mock JSON file.
Create a test that will first import the entire localStorage and then test the following:
- Address book
- Custom apps
- Safes sidebar

**Comment by liliya-soroka** [comment]
@katspaugh , @francovenica , I have a few questions:
1. will this case be used only for migration from "multinetworks apps" to "one app with all networks,"  or will it be possible to use this case each time during regression?

2. will it cover all our needs ( all cases: only Mainnet/all networks/ Mainnet+oneL2 network..." required for testing migration to one app?

**Comment by francovenica** [comment]
> @katspaugh , @francovenica , I have a few questions:
> 
> 1. will this case be used only for migration from "multinetworks apps" to "one app with all networks,"  or will it be possible to use this case each time during regression?
> 2. will it cover all our needs for migration to one app for all networks?( all cases: only Mainnet/all networks/ Mainnet+oneL2 network..." required for testing migration to one app?

Better late than never.
What this test does is populate the storage and then checks in the UI that the values are there. (remember that this test always start with a clean browser with no storage)
If someday the devs decide to change the name of the keys or how the values of those keys are formatted then this test will fail and will have to be modified
